### DISCUSSION TITLE
How to create a color animation with C# code?

### DISCUSSION THREAD

**Discussion by YBCA7** [dotnet/wpf#10240] [Q&A] [answered]
I've tried this before:
![Screenshot_20250108_223948.jpg](https://github.com/user-attachments/assets/8239041d-1f61-4583-bcb5-618a006e83f6)
However, every time I call this function, the window is **unresponsive**. The AI thinks it's blocked by the UI thread, but there's **only one animation**, so it can't be blocked. What should I do?
And how to create two animations at the same time?

**Comment by miloush** [comment, marked as answer]
Can you provide some demo application exhibiting the issue?

**Reply by YBCA7** [reply]
Yes.

[Lottery](https://github.com/Unqualified-Developers/Lottery/tree/dev)

**Reply by YBCA7** [reply]
You will find two animations. However, removing one of them didn't work.

**Reply by miloush** [reply]
Hm, I can barely reproduce the issue. I think it happened to me once or twice that the cursor froze as I changed focus from text box to text box, but it's hard to consistently get it. I am not sure I would blame the animations, at least for me they seem to be animating fine, it was the focus change. Also I tried to make the animations both a second longer and could not reproduce the freeze. Another very confusing thing is that during the freeze, mouse cursor does not move at all in the window. I haven't really seen that, and I am a bit doubtful that any blocking of UI thread on WPF side would cause that. I might be wrong though, do you have repro steps that make it freeze? Does it freeze for you with long animations too?

**Reply by YBCA7** [reply]
Well, I don't think it's going to be difficult to recreate the problem.
https://github.com/user-attachments/assets/93211a10-e349-4867-9c62-811a59b95d92

**Reply by miloush** [reply]
That is a crash, not a freeze. When I do what you do on the video, the message box appears.

![image](https://github.com/user-attachments/assets/72635b19-6793-4829-bdac-0f20c2c4fc4f)

 When you run it from a Visual Studio/debugger, does it not show you what the exception is?

**Reply by h3xds1nz** [reply]
You could also grab the exception from `Event Viewer` (Run -> eventvwr) `-> Windows Logs -> Application `retrospectively (looking for .NET as source).

Would be also good to know if it reproduces on latest .NET given that you're on .NET Framework v4.8.

**Reply by YBCA7** [reply]
You had no problems executing the latest code in `dev` branch, including `ColorAnimation` ? Maybe I was unlucky.

**Reply by miloush** [reply]
Correct, tried again now and still working.

> Maybe I was unlucky.

This is software, not a lottery. If it is crashing for you, it might be for other people, it would be good to figure out the reason. Can you find the crash in Event Viewer like h3xds1nz suggested?

**Reply by YBCA7** [reply]
That's unbelievable.
I updated my system to Windows 10, and now it can work properly.
However, when my friend who uses Windows 7 tried, he couldn't run it either.

**Reply by miloush** [reply]
You didn't say Windows 7 was involved. The issue might have been fixed in later .NET Framework versions, but without knowing what the exception being thrown is, we don't know what the issue is or whether it can be fixed/workarounded.

**Reply by YBCA7** [reply]
Do you know what is wrong with the workflow file?
It can't work now.

**Reply by miloush** [reply]
I don't see anything wrong. We suggested you either reproduce the error under debugger, or check the Event Viewer, or you can get a crash dump. Without a repro, there isn't much we can do.

**Reply by YBCA7** [reply]
The same repo.

**Reply by miloush** [reply]
rep**r**o is a short for steps to reproduce the problem. Provide one of the things we asked for and then we can see.

**Reply by YBCA7** [reply]
[Workflow File](https://github.com/Unqualified-Developers/Lottery/blob/dev/.github/workflows/dotnet-desktop.yml)
[Information](https://github.com/Unqualified-Developers/Lottery/actions/runs/12731316809)

**Reply by miloush** [reply]
Ah sorry misunderstood what you are having troubles with. Well it says there is no project to build. After you checkout, do you not need to run the msbuild from the src folder?

**Reply by YBCA7** [reply]
Thanks for your support.
There is something wrong with the settings of file path.
I don't know what is a correct one.

**Reply by YBCA7** [reply]
More clearly:
You see, the solution file really exists in src dict.
However, it couldn't be found when the workflow ran.

**Reply by YBCA7** [reply]
I want to build the project on push so that it can check the code.

**Reply by YBCA7** [reply]
If you know how to do, you can create a pull request in the repo.

**Reply by miloush** [reply]
make sure it works for you locally trying to run the commands in the workflow; I am past several deadlines this week and not an expert on workflows, if anybody else wants to chime in, feel free (@lindexi?)

**Reply by lindexi** [reply]
I guess it is not the workflow issues. But I do not any ideas. As https://github.com/dotnet/wpf/discussions/10240#discussioncomment-11786836 shows, it is the crash issues, and I think it would be better to just hang debugging and understand the cause of the crash.

我猜不是工作流的问题，但我没有什么想法。我认为直接挂调试了解程序崩溃的原因会更好

**Reply by YBCA7** [reply]
> I guess it is not the workflow issues. But I do not any ideas. As https://github.com/dotnet/wpf/discussions/10240#discussioncomment-11786836 shows, it is the crash issues, and I think it would be better to just hang debugging and understand the cause of the crash.
> 
> 我猜不是工作流的问题，但我没有什么想法。我认为直接挂调试了解程序崩溃的原因会更好
> 
> 

I'm sure this is a workflow issue, because I can successfully compile this project using Visual Studio.

我确定这是工作流的问题，因为我用Visual Studio可以成功地编译这个项目。

**Reply by YBCA7** [reply]
@lindexi 

This is a new question, unrelated to the above issue about program crashes, which has been fixed.

这是一个新的问题，与上述有关程序崩溃的问题无关，崩溃的问题已被修复。

**Reply by lindexi** [reply]
@YBCA7 As https://github.com/Unqualified-Developers/Lottery/actions/runs/12731316809/job/35485171488 shows, it fails in Execute unit tests:

> Run dotnet test
> MSBUILD : error MSB[10](https://github.com/Unqualified-Developers/Lottery/actions/runs/12731316809/job/35485171488#step:5:11)03: Specify a project or solution file. The current working directory does not contain a project or solution file.
Error: Process completed with exit code 1.

Feel free to remove this step in https://github.com/Unqualified-Developers/Lottery/blob/97e4684cb4998af32434bf5f0861b7e6e5100a12/.github/workflows/dotnet-desktop.yml#L79-L82

流水其实是构建成功的，只是在跑测试这一步挂了而已。这一步挂了的原因是你的项目没有单元测试，将其干掉就好了。删掉 dotnet-desktop.yml 的第 79 到 82 行试试。或者是将 79 行之后的内容都删掉


```yml
name: .NET Core Desktop

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Lottery.sln                      # Replace with your solution name, i.e. MyWpfApp.sln.
      # Test_Project_Path: Lottery.csproj  # Do not have the test project, ignore.
      # Wap_Project_Directory: .\    # Do not have the wap project, ignore.
      # Wap_Project_Path: .\         # Do not have the wap project, ignore.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build the application
    - name: Restore the application
      run: msbuild -restore /p:Configuration=$env:Configuration $env:Solution_Name
      env:
        Configuration: ${{ matrix.configuration }}
```

PS: I do not run or test this dotnet-desktop.yml code.

PS: 以上给的代码我自己没有跑过和测试哈，还请试试看，哪里挂了再和我说
