### ISSUE TITLE
After updating 7.0.0-rc.1 to 7.0.0-rc.2 build fails

### ISSUE THREAD

**Issue by BieleckiLtd** [dotnet/wpf#7216]
After updating 7.0.0-rc.1 to 7.0.0-rc.2 my WPF application build action

`dotnet build xxxWpf/xxxWpf.csproj -c Release -p:PublishSingleFile=true --no-restore`

started to fail with the following error:

```
Error: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file 'D:\a\xxx\xxx\xxxModels\obj\project.assets.json' doesn't have a target for 'net7.0/win-x64'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project. You may also need to include 'win-x64' in your project's RuntimeIdentifiers. [D:\a\xxx\xxx\xxxModels\xxxModels.csproj]
```

Above xxxModels project already targets net7.0 and is referenced by the main WPF project. I tried updating all Microsoft.Extensions.* packages references to 7.0.0-rc.2.* but that didn't help. Prior 11 October 2022 (7.0.0-rc.1) build was not failing.

Section from xxxWpf.csproj:
```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Icon\icon512.ico</ApplicationIcon>
    <AssemblyName>X X X</AssemblyName>
	  <RootNameSpace>xxxWpf</RootNameSpace>
	  <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
	  <SelfContained>true</SelfContained>
  </PropertyGroup>
```
Section from xxxModels.csproj:
```
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
```

**Comment by ThomasGoulet73** [comment]
@BieleckiLtd Did you invoke restore on your project before the command line you provided includes `--no-restore` which disables restore during build. The error includes "Ensure that restore has run..." so my guess is that you need to invoke restore on your project. You can either remove `--no-restore` or invoke restore on your project manually "dotnet restore ...".

**Comment by BieleckiLtd** [comment]
Yes, I do restore in previous step. Complete job looks like that:

```
jobs:
  deploy:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          include-prerelease: true
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -p:PublishSingleFile=true --no-restore
      
      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --output ./${{ env.PUBLISH_PATH }} --no-build

      - name: Remove the .pdb files
        run: Remove-Item -path ${{ env.PUBLISH_PATH }}/*.pdb
      
      - name: Create archive with all remaining files
        run: Compress-Archive -path ${{ env.PUBLISH_PATH }}/* -destinationPath "$($env:GITHUB_REF -replace "refs/tags/").zip" #tag name is file name at the same time

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      
      - name: Copy archives to Release
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "*.zip"
          release-url: ${{ steps.create_release.outputs.upload_url }}
```
